import { Player, Group, WatchlistEntry, EventLog, AlertNotification, AuditRecord, ServerOverview } from "@/types";

export const initialServerOverview: ServerOverview = {
  isOnline: true,
  playersOnline: 127,
  maxSlots: 256,
  watchedOnline: 8,
  watchedGroupsOnline: 3,
  activeAlertsCount: 4,
  playersEnteredToday: 412,
  playersExitedToday: 285,
  averageSessionDurationSec: 8740, // ~2h 25m
  uptimeHours: 38,
  serverPing: 34,
  lastHeartbeat: new Date().toISOString(),
};

export const initialPlayers: Player[] = [
  {
    id: "ply-001",
    license: "license:4a89df8812c37e9091a271bb8912c930",
    steam: "steam:110000109fa7210",
    discordId: "389102938172635412",
    xbox: "xbox:2535418902341209",
    live: "live:881920391283",
    rockstar: "rockstar:91823091",
    ipAddress: "192.168.1.104",
    isOnline: true,
    currentServerId: 128,
    currentArea: "Pillbox Hill / Downtown LS",
    currentVehicle: "Sultan RS [B4DS-01]",
    ping: 42,
    firstSeen: "2026-03-12T08:00:00Z",
    lastSeen: new Date().toISOString(),
    isWatchlisted: true,
    watchlistPriority: "HIGH",
    groupName: "BADside",
    characters: [
      {
        id: "char-245",
        playerId: "ply-001",
        characterId: 245,
        firstName: "John",
        lastName: "Smith",
        fullName: "John Smith",
        job: "Unemployed",
        jobGrade: "Street Boss",
        faction: "BADside",
        cash: 45200,
        bank: 890500,
        phoneNumber: "555-0192",
        dateCreated: "2026-03-12",
        lastSeen: new Date().toISOString(),
        isActive: true,
      },
      {
        id: "char-891",
        playerId: "ply-001",
        characterId: 891,
        firstName: "Officer",
        lastName: "Smith",
        fullName: "Jonathan Smith",
        job: "Police",
        jobGrade: "Senior Officer",
        faction: "LSPD",
        cash: 12000,
        bank: 340000,
        phoneNumber: "555-0811",
        dateCreated: "2026-04-01",
        lastSeen: "2026-10-05T14:30:00Z",
        isActive: false,
      }
    ],
    currentSession: {
      id: "sess-1001",
      playerId: "ply-001",
      characterId: "char-245",
      characterName: "John Smith",
      serverId: 128,
      joinedAt: new Date(Date.now() - 4 * 3600 * 1000 - 21 * 60 * 1000 - 32 * 1000).toISOString(), // 4h 21m 32s ago
      durationSec: 15692,
      lastHeartbeat: new Date().toISOString(),
      currentArea: "Pillbox Hill / Downtown LS",
      currentVehicle: "Sultan RS [B4DS-01]",
    }
  },
  {
    id: "ply-002",
    license: "license:7c91fa0233b45e11029c882a1739c910",
    steam: "steam:110000109c11822",
    discordId: "492109283719283019",
    xbox: "xbox:1928301928301928",
    live: "live:918239019283",
    rockstar: "rockstar:10928301",
    ipAddress: "10.0.1.22",
    isOnline: true,
    currentServerId: 44,
    currentArea: "Little Seoul / Palomino Ave",
    currentVehicle: "Elegy Retro Custom",
    ping: 38,
    firstSeen: "2026-02-10T12:00:00Z",
    lastSeen: new Date().toISOString(),
    isWatchlisted: true,
    watchlistPriority: "MEDIUM",
    groupName: "BADside",
    characters: [
      {
        id: "char-188",
        playerId: "ply-002",
        characterId: 188,
        firstName: "Michael",
        lastName: "Carter",
        fullName: "Michael Carter",
        job: "Mechanic",
        jobGrade: "Lead Tuner",
        faction: "BADside",
        cash: 18000,
        bank: 450000,
        phoneNumber: "555-0422",
        dateCreated: "2026-02-10",
        lastSeen: new Date().toISOString(),
        isActive: true,
      }
    ],
    currentSession: {
      id: "sess-1002",
      playerId: "ply-002",
      characterId: "char-188",
      characterName: "Michael Carter",
      serverId: 44,
      joinedAt: new Date(Date.now() - 1 * 3600 * 1000 - 12 * 60 * 1000).toISOString(), // 1h 12m ago
      durationSec: 4320,
      lastHeartbeat: new Date().toISOString(),
      currentArea: "Little Seoul / Palomino Ave",
      currentVehicle: "Elegy Retro Custom",
    }
  },
  {
    id: "ply-003",
    license: "license:9a33dd4455bb66cc77dd88ee99ff00aa",
    steam: "steam:1100001088ef412",
    discordId: "819203918273645102",
    ipAddress: "172.16.0.45",
    isOnline: true,
    currentServerId: 72,
    currentArea: "Vinewood Hills / Observatory",
    currentVehicle: "Toros [VIP-77]",
    ping: 55,
    firstSeen: "2026-01-05T10:00:00Z",
    lastSeen: new Date().toISOString(),
    isWatchlisted: true,
    watchlistPriority: "HIGH",
    groupName: "BADside",
    characters: [
      {
        id: "char-902",
        playerId: "ply-003",
        characterId: 902,
        firstName: "David",
        lastName: "King",
        fullName: "David King",
        job: "Businessman",
        jobGrade: "Director",
        faction: "BADside",
        cash: 125000,
        bank: 4500000,
        phoneNumber: "555-0999",
        dateCreated: "2026-01-05",
        lastSeen: new Date().toISOString(),
        isActive: true,
      }
    ],
    currentSession: {
      id: "sess-1003",
      playerId: "ply-003",
      characterId: "char-902",
      characterName: "David King",
      serverId: 72,
      joinedAt: new Date(Date.now() - 4 * 3600 * 1000 - 42 * 60 * 1000).toISOString(), // 4h 42m ago
      durationSec: 16920,
      lastHeartbeat: new Date().toISOString(),
      currentArea: "Vinewood Hills / Observatory",
      currentVehicle: "Toros [VIP-77]",
    }
  },
  {
    id: "ply-004",
    license: "license:1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e",
    steam: "steam:1100001054ab339",
    discordId: "678901234567890123",
    ipAddress: "192.168.2.14",
    isOnline: true,
    currentServerId: 19,
    currentArea: "Sandy Shores / Alamo Sea",
    currentVehicle: "Kamacho Offroad",
    ping: 28,
    firstSeen: "2026-05-18T16:00:00Z",
    lastSeen: new Date().toISOString(),
    isWatchlisted: false,
    groupName: "BADside",
    characters: [
      {
        id: "char-341",
        playerId: "ply-004",
        characterId: 341,
        firstName: "Alex",
        lastName: "Morgan",
        fullName: "Alex Morgan",
        job: "Unemployed",
        jobGrade: "Member",
        faction: "BADside",
        cash: 23000,
        bank: 310000,
        phoneNumber: "555-0341",
        dateCreated: "2026-05-18",
        lastSeen: new Date().toISOString(),
        isActive: true,
      }
    ],
    currentSession: {
      id: "sess-1004",
      playerId: "ply-004",
      characterId: "char-341",
      characterName: "Alex Morgan",
      serverId: 19,
      joinedAt: new Date(Date.now() - 51 * 60 * 1000).toISOString(), // 51m ago
      durationSec: 3060,
      lastHeartbeat: new Date().toISOString(),
      currentArea: "Sandy Shores / Alamo Sea",
      currentVehicle: "Kamacho Offroad",
    }
  },
  {
    id: "ply-005",
    license: "license:8877665544332211aabbccddeeff0011",
    steam: "steam:110000109923811",
    discordId: "987654321098765432",
    ipAddress: "192.168.0.88",
    isOnline: true,
    currentServerId: 67,
    currentArea: "Mission Row / Police Dept",
    currentVehicle: "Vapid Stanier Cruiser #21",
    ping: 35,
    firstSeen: "2026-02-01T09:00:00Z",
    lastSeen: new Date().toISOString(),
    isWatchlisted: false,
    groupName: "LSPD",
    characters: [
      {
        id: "char-501",
        playerId: "ply-005",
        characterId: 501,
        firstName: "Marcus",
        lastName: "Vance",
        fullName: "Marcus Vance",
        job: "Police",
        jobGrade: "Captain",
        faction: "LSPD",
        cash: 8500,
        bank: 620000,
        phoneNumber: "555-0501",
        dateCreated: "2026-02-01",
        lastSeen: new Date().toISOString(),
        isActive: true,
      }
    ],
    currentSession: {
      id: "sess-1005",
      playerId: "ply-005",
      characterId: "char-501",
      characterName: "Marcus Vance",
      serverId: 67,
      joinedAt: new Date(Date.now() - 3 * 3600 * 1000 - 15 * 60 * 1000).toISOString(),
      durationSec: 11700,
      lastHeartbeat: new Date().toISOString(),
      currentArea: "Mission Row / Police Dept",
      currentVehicle: "Vapid Stanier Cruiser #21",
    }
  },
  {
    id: "ply-006",
    license: "license:ffeeddccbbaa99887766554433221100",
    steam: "steam:110000102391028",
    discordId: "123098456789123456",
    ipAddress: "10.10.10.5",
    isOnline: false,
    currentServerId: undefined,
    currentArea: "Offline",
    ping: 0,
    firstSeen: "2026-04-10T11:00:00Z",
    lastSeen: "2026-10-07T09:45:00Z",
    isWatchlisted: true,
    watchlistPriority: "LOW",
    groupName: "BADside",
    characters: [
      {
        id: "char-812",
        playerId: "ply-006",
        characterId: 812,
        firstName: "Kaelen",
        lastName: "Cross",
        fullName: "Kaelen Cross",
        job: "Unemployed",
        jobGrade: "Associate",
        faction: "BADside",
        cash: 5400,
        bank: 120000,
        phoneNumber: "555-0812",
        dateCreated: "2026-04-10",
        lastSeen: "2026-10-07T09:45:00Z",
        isActive: false,
      }
    ]
  },
  {
    id: "ply-007",
    license: "license:554433221100ffeeddccbbaa99887766",
    steam: "steam:110000104455667",
    discordId: "556677889900112233",
    ipAddress: "172.20.10.2",
    isOnline: true,
    currentServerId: 104,
    currentArea: "Davis / Grove Street",
    currentVehicle: "Bravado Buffalo STX",
    ping: 48,
    firstSeen: "2026-06-01T15:00:00Z",
    lastSeen: new Date().toISOString(),
    isWatchlisted: false,
    groupName: "Ballas Syndicate",
    characters: [
      {
        id: "char-667",
        playerId: "ply-007",
        characterId: 667,
        firstName: "Trevon",
        lastName: "Hayes",
        fullName: "Trevon Hayes",
        job: "Unemployed",
        jobGrade: "Enforcer",
        faction: "Ballas",
        cash: 31000,
        bank: 290000,
        phoneNumber: "555-0667",
        dateCreated: "2026-06-01",
        lastSeen: new Date().toISOString(),
        isActive: true,
      }
    ],
    currentSession: {
      id: "sess-1007",
      playerId: "ply-007",
      characterId: "char-667",
      characterName: "Trevon Hayes",
      serverId: 104,
      joinedAt: new Date(Date.now() - 1 * 3600 * 1000 - 45 * 60 * 1000).toISOString(),
      durationSec: 6300,
      lastHeartbeat: new Date().toISOString(),
      currentArea: "Davis / Grove Street",
      currentVehicle: "Bravado Buffalo STX",
    }
  },
  {
    id: "ply-008",
    license: "license:33221100ffeeddccbbaa998877665544",
    steam: "steam:110000108899001",
    discordId: "778899001122334455",
    ipAddress: "192.168.10.99",
    isOnline: true,
    currentServerId: 58,
    currentArea: "Mount Zonah Medical Center",
    currentVehicle: "Brute Ambulance Unit 04",
    ping: 39,
    firstSeen: "2026-01-20T08:00:00Z",
    lastSeen: new Date().toISOString(),
    isWatchlisted: false,
    groupName: "EMS",
    characters: [
      {
        id: "char-412",
        playerId: "ply-008",
        characterId: 412,
        firstName: "Dr. Sarah",
        lastName: "Connor",
        fullName: "Sarah Connor",
        job: "Ambulance",
        jobGrade: "Chief Medical Officer",
        faction: "EMS",
        cash: 15400,
        bank: 780000,
        phoneNumber: "555-0412",
        dateCreated: "2026-01-20",
        lastSeen: new Date().toISOString(),
        isActive: true,
      }
    ],
    currentSession: {
      id: "sess-1008",
      playerId: "ply-008",
      characterId: "char-412",
      characterName: "Sarah Connor",
      serverId: 58,
      joinedAt: new Date(Date.now() - 2 * 3600 * 1000 - 10 * 60 * 1000).toISOString(),
      durationSec: 7800,
      lastHeartbeat: new Date().toISOString(),
      currentArea: "Mount Zonah Medical Center",
      currentVehicle: "Brute Ambulance Unit 04",
    }
  }
];

export const initialGroups: Group[] = [
  {
    id: "grp-badside",
    name: "BADside",
    slug: "badside",
    tag: "[BAD]",
    description: "Underground crime syndicate operating across Pillbox, Little Seoul, and Vinewood Hills.",
    color: "#8B5CF6", // Badside purple
    priority: "HIGH",
    discordRoleId: "9823412091823901",
    onlineCount: 8,
    totalSessionTodaySec: 123680, // 34h 21m
    lastActivity: "10:52:32",
    members: [
      {
        id: "gm-01",
        groupId: "grp-badside",
        playerId: "ply-001",
        playerName: "John Smith",
        characterId: 245,
        characterName: "John Smith",
        roleTitle: "Syndicate Boss",
        status: "ACTIVE",
        isOnline: true,
        currentSessionDurationSec: 15692,
        addedAt: "2026-03-12"
      },
      {
        id: "gm-02",
        groupId: "grp-badside",
        playerId: "ply-002",
        playerName: "Michael Carter",
        characterId: 188,
        characterName: "Michael Carter",
        roleTitle: "Underboss",
        status: "ACTIVE",
        isOnline: true,
        currentSessionDurationSec: 4320,
        addedAt: "2026-02-10"
      },
      {
        id: "gm-03",
        groupId: "grp-badside",
        playerId: "ply-003",
        playerName: "David King",
        characterId: 902,
        characterName: "David King",
        roleTitle: "Capo / Logistics",
        status: "ACTIVE",
        isOnline: true,
        currentSessionDurationSec: 16920,
        addedAt: "2026-01-05"
      },
      {
        id: "gm-04",
        groupId: "grp-badside",
        playerId: "ply-004",
        playerName: "Alex Morgan",
        characterId: 341,
        characterName: "Alex Morgan",
        roleTitle: "Enforcer",
        status: "ACTIVE",
        isOnline: true,
        currentSessionDurationSec: 3060,
        addedAt: "2026-05-18"
      },
      {
        id: "gm-05",
        groupId: "grp-badside",
        playerId: "ply-006",
        playerName: "Kaelen Cross",
        characterId: 812,
        characterName: "Kaelen Cross",
        roleTitle: "Associate",
        status: "ACTIVE",
        isOnline: false,
        addedAt: "2026-04-10"
      }
    ]
  },
  {
    id: "grp-lspd",
    name: "Los Santos Police Dept",
    slug: "lspd",
    tag: "[PD]",
    description: "Metropolitan law enforcement agency safeguarding Los Santos County.",
    color: "#38BDF8", // Cyan
    priority: "MEDIUM",
    discordRoleId: "1234567890123456",
    onlineCount: 14,
    totalSessionTodaySec: 172800,
    lastActivity: "11:15:00",
    members: []
  },
  {
    id: "grp-ems",
    name: "Los Santos Medical Services",
    slug: "ems",
    tag: "[EMS]",
    description: "Emergency Medical Services and Pillbox General triage unit.",
    color: "#10B981", // Emerald
    priority: "LOW",
    discordRoleId: "2345678901234567",
    onlineCount: 6,
    totalSessionTodaySec: 79200,
    lastActivity: "11:12:00",
    members: []
  },
  {
    id: "grp-ballas",
    name: "Ballas Syndicate",
    slug: "ballas",
    tag: "[BLS]",
    description: "South Central territorial syndicate dominating Davis and Strawberry.",
    color: "#EC4899", // Pink/Magenta
    priority: "HIGH",
    discordRoleId: "3456789012345678",
    onlineCount: 5,
    totalSessionTodaySec: 64800,
    lastActivity: "10:45:00",
    members: []
  }
];

export const initialWatchlist: WatchlistEntry[] = [
  {
    id: "wl-01",
    targetType: "GROUP",
    targetId: "grp-badside",
    targetName: "BADside Group Syndicate",
    priority: "HIGH",
    category: "SYNDICATE",
    reason: "Underground syndicate with high firearm trafficking suspicion; monitor mass gatherings.",
    notes: "Requires mandatory dispatch notification if >5 members connect simultaneously.",
    createdBy: "SOC_DIRECTOR",
    isActive: true,
    createdAt: "2026-09-01T00:00:00Z"
  },
  {
    id: "wl-02",
    targetType: "PLAYER",
    targetId: "ply-001",
    targetName: "John Smith (CID #245)",
    priority: "HIGH",
    category: "HIGH_VALUE",
    reason: "Key decision maker for BADside operations. Linked to major server incidents.",
    notes: "Frequently switches between Civilian Sultan RS and police secondary character.",
    createdBy: "CHIEF_STAFF",
    isActive: true,
    createdAt: "2026-09-10T12:00:00Z"
  },
  {
    id: "wl-03",
    targetType: "PLAYER",
    targetId: "ply-002",
    targetName: "Michael Carter (CID #188)",
    priority: "MEDIUM",
    category: "SUSPECT",
    reason: "Logistics specialist, suspicious vehicle modifications tracking.",
    notes: "Monitored for sudden cash spikes.",
    createdBy: "MOD_ALEX",
    isActive: true,
    createdAt: "2026-09-18T15:30:00Z"
  },
  {
    id: "wl-04",
    targetType: "PLAYER",
    targetId: "ply-006",
    targetName: "Kaelen Cross (CID #812)",
    priority: "LOW",
    category: "INVESTIGATION",
    reason: "Associate with periodic connection dropouts.",
    notes: "Keep on passive radar.",
    createdBy: "STAFF_BOT",
    isActive: true,
    createdAt: "2026-10-01T08:00:00Z"
  }
];

export const initialAlerts: AlertNotification[] = [
  {
    id: "alt-01",
    type: "WATCHLIST_ONLINE",
    playerId: "ply-001",
    characterName: "John Smith",
    groupName: "BADside",
    title: "WATCHLIST PLAYER DETECTED",
    message: "High-priority target John Smith (#245) joined city. Server ID: 128 at Pillbox Hill.",
    severity: "CRITICAL",
    isRead: false,
    createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString()
  },
  {
    id: "alt-02",
    type: "GROUP_MASS_ONLINE",
    groupName: "BADside",
    title: "GROUP MASS CONVERGENCE",
    message: "8 BADside members are currently online simultaneously in downtown grid.",
    severity: "CRITICAL",
    isRead: false,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString()
  },
  {
    id: "alt-03",
    type: "CHAR_CHANGED",
    playerId: "ply-001",
    characterName: "John Smith",
    title: "CHARACTER PROFILE SWITCH",
    message: "Player John Smith switched active character from CID #891 (Officer) to CID #245 (BADside).",
    severity: "WARNING",
    isRead: true,
    createdAt: new Date(Date.now() - 72 * 60 * 1000).toISOString()
  },
  {
    id: "alt-04",
    type: "ROLE_CHANGED",
    playerId: "ply-002",
    characterName: "Michael Carter",
    title: "DISCORD ROLE UPDATE",
    message: "Discord permissions updated: Added role @BADside High Command to user Michael Carter.",
    severity: "INFO",
    isRead: true,
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString()
  }
];

export const initialEvents: EventLog[] = [
  {
    id: "evt-01",
    playerId: "ply-001",
    playerName: "John Smith",
    eventType: "JOIN_CITY",
    eventData: "Player connected to Server #128 via license:4a89df8812c37e9091a271bb8912c930",
    location: "Pillbox Hill",
    severity: "INFO",
    timestamp: "10:42:15"
  },
  {
    id: "evt-02",
    playerId: "ply-001",
    playerName: "John Smith",
    eventType: "CHAR_SWITCH",
    eventData: "Loaded Character: John Smith (CID #245) [BADside Boss]",
    location: "Legion Square",
    severity: "INFO",
    timestamp: "10:43:02"
  },
  {
    id: "evt-03",
    playerId: "ply-001",
    playerName: "John Smith",
    eventType: "VEHICLE_CHANGE",
    eventData: "Entered vehicle: Sultan RS (Plate: B4DS-01)",
    location: "Alta Street Garage",
    severity: "NOTICE",
    timestamp: "10:48:30"
  },
  {
    id: "evt-04",
    playerId: "ply-001",
    playerName: "John Smith",
    eventType: "DISTRICT_MOVE",
    eventData: "Traversed into Downtown Los Santos / Maze Bank Arena perimeter",
    location: "Downtown Los Santos",
    severity: "INFO",
    timestamp: "11:02:18"
  },
  {
    id: "evt-05",
    playerId: "ply-006",
    playerName: "Kaelen Cross",
    eventType: "LEAVE_CITY",
    eventData: "Player disconnected gracefully (Reason: Exiting / Game Quit)",
    location: "Del Perro Freeway",
    severity: "NOTICE",
    timestamp: "10:37:44"
  },
  {
    id: "evt-06",
    playerId: "ply-002",
    playerName: "Michael Carter",
    eventType: "JOIN_CITY",
    eventData: "Connected to Server #44 with ping 38ms",
    location: "Little Seoul",
    severity: "INFO",
    timestamp: "10:31:00"
  }
];

export const initialAuditLogs: AuditRecord[] = [
  {
    id: "aud-01",
    staffId: "staff-99",
    staffName: "Chief James Gordon",
    action: "REVEAL_IDENTIFIER",
    target: "John Smith (ply-001)",
    metadata: "Revealed FiveM License: license:4a89df8812c37e9091a271bb8912c930 and Steam Hex",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString()
  },
  {
    id: "aud-02",
    staffId: "staff-12",
    staffName: "Staff Moderator Alex",
    action: "ADD_WATCHLIST",
    target: "David King (ply-003)",
    metadata: "Elevated priority to HIGH (Suspected syndicate financier)",
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString()
  }
];
